version: '3'

services: 
  db_thealfastore: 
    container_name: db_thealfastore
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_thealfastore
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}
